openapi: 3.0.2
info:
  version: 1.0.0
  title: Picture Hash
  license:
    name: Apache 2.0
servers:
  - url:  /ds-pictureHash/api
paths:
  # Displays the DHash value given an URL like
  #   http://localhost:8080/ds-pictureHash/api/imageDHash/imgPath/?imgPath=<path to the image>
  /imageDHash/imgPath:
    get:
      summary: 'Request imageDPHash from an image at the Royal Danish Library'
      operationId: getImageDHash
      parameters:
        - name: imgPath
          in: query
          description: 'Path for the image found in Cumulus image server'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'TheDHash value for the image'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HashReply'
  # Displays the PHash value given an URL like
  #   http://localhost:8080/ds-pictureHash/api/imagePHash/imgPath/?imgPath=<path to the image>
  /imagePHash/imgPath:
    get:
      summary: 'Request image PHash from an image at the Royal Danish Library'
      operationId: getImagePHash
      parameters:
        - name: imgPath
          in: query
          description: 'Path for the image found in Cumulus image server'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'ThePHash value for the image'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HashReply'
components:
  schemas:
    HashReply:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Hash value from the API
